language: java
install: true
sudo: required
# Travis add-ons.
addons:
  ssh_known_hosts: 5.196.65.205
  chrome: stable
  apt:
    packages:
      - jq
      - wget
      - curl
      - libssl1.0.0
      - sshpass
services:
  - docker
  - xvfb
script:
  - mvn package -q
after_success:
  # Update official "blockchain2graph bitcoin neo4j" image.
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push straumat/blockchain2graph-bitcoin-neo4j
  # Run benchmark of "blockchain2graph bitcoin neo4j".
  # - docker push $DOCKER_USERNAME/blockchain2graph-bitcoin-neo4j-benchmark
  # - RELEASE=`cat pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}'`
  # - sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker stop $(docker ps -aq --filter "label=blockchain2graph-bitcoin-neo4j-benchmark")'
  # - sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker rm -f $(docker ps -aq --filter "label=blockchain2graph-bitcoin-neo4j-benchmark")'
  # - sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "docker pull straumat/blockchain2graph-bitcoin-neo4j-benchmark:$RELEASE"
  # - sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "nohup docker run -l blockchain2graph-bitcoin-neo4j-benchmark --security-opt apparmor=unconfined -e SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD -e SPRING_DATA_NEO4J_URI=file:///graph.db -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER straumat/blockchain2graph-bitcoin-neo4j-benchmark:$RELEASE > /home/ci/logs-ci &"
